services:

  postgres:

    image: postgres:17

    container_name: agentic-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agentic_ai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:

    build:
      context: ..
      dockerfile: docker/dockerfile.backend

    container_name: agentic-backend

    restart: always

    env_file:
      - ../.env.docker

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"

    volumes:
      - ../:/app


  frontend:

    build:
      context: ..
      dockerfile: docker/dockerfile.frontend

    container_name: agentic-frontend

    restart: always

    depends_on:
      backend:
        condition: service_started

    environment:
      BACKEND_URL: http://backend:8000

    ports:
      - "8501:8501"

    volumes:
      - ../frontend:/frontend


volumes:

  postgres_data: